# display mode bit flags
FULLSCREEN: int
DOUBLEBUF: int
HWSURFACE: int
OPENGL: int
RESIZABLE: int
NOFRAME: int
SCALED: int

# event type ids
QUIT: int
ACTIVEEVENT: int
KEYDOWN: int
KEYUP: int
MOUSEMOTION: int
MOUSEBUTTONUP: int
MOUSEBUTTONDOWN: int
JOYAXISMOTION: int
JOYBALLMOTION: int
JOYHATMOTION: int
JOYBUTTONUP: int
JOYBUTTONDOWN: int
VIDEORESIZE: int
VIDEOEXPOSE: int
USEREVENT: int
AUDIODEVICEADDED: int
AUDIODEVICEREMOVED: int
FINGERMOTION: int
FINGERDOWN: int
FINGERUP: int
MULTIGESTURE: int
TEXTEDITING: int
TEXTINPUT: int
DROPBEGIN: int
DROPCOMPLETE: int
DROPFILE: int
DROPTEXT: int
MIDIIN: int
MIDIOUT: int
NUMEVENTS: int

# Times in pygame are represented in milliseconds (1/1000 seconds).
# Most platforms have a limited time resolution of around 10 milliseconds.
# This resolution, in milliseconds, is given in the TIMER_RESOLUTION constant.
TIMER_RESOLUTION: int

# an integer ID representing every key on the keyboard
K_BACKSPACE: int
K_TAB: int
K_CLEAR: int
K_RETURN: int
K_PAUSE: int
K_ESCAPE: int
K_SPACE: int
K_EXCLAIM: int
K_QUOTEDBL: int
K_HASH: int
K_DOLLAR: int
K_AMPERSAND: int
K_QUOTE: int
K_LEFTPAREN: int
K_RIGHTPAREN: int
K_ASTERISK: int
K_PLUS: int
K_COMMA: int
K_MINUS: int
K_PERIOD: int
K_SLASH: int
K_0: int
K_1: int
K_2: int
K_3: int
K_4: int
K_5: int
K_6: int
K_7: int
K_8: int
K_9: int
K_COLON: int
K_SEMICOLON: int
K_LESS: int
K_EQUALS: int
K_GREATER: int
K_QUESTION: int
K_AT: int
K_LEFTBRACKET: int
K_BACKSLASH: int
K_RIGHTBRACKET: int
K_CARET: int
K_UNDERSCORE: int
K_BACKQUOTE: int
K_a: int
K_b: int
K_c: int
K_d: int
K_e: int
K_f: int
K_g: int
K_h: int
K_i: int
K_j: int
K_k: int
K_l: int
K_m: int
K_n: int
K_o: int
K_p: int
K_q: int
K_r: int
K_s: int
K_t: int
K_u: int
K_v: int
K_w: int
K_x: int
K_y: int
K_z: int
K_DELETE: int
K_KP0: int
K_KP1: int
K_KP2: int
K_KP3: int
K_KP4: int
K_KP5: int
K_KP6: int
K_KP7: int
K_KP8: int
K_KP9: int
K_KP_PERIOD: int
K_KP_DIVIDE: int
K_KP_MULTIPLY: int
K_KP_MINUS: int
K_KP_PLUS: int
K_KP_ENTER: int
K_KP_EQUALS: int
K_UP: int
K_DOWN: int
K_RIGHT: int
K_LEFT: int
K_INSERT: int
K_HOME: int
K_END: int
K_PAGEUP: int
K_PAGEDOWN: int
K_F1: int
K_F2: int
K_F3: int
K_F4: int
K_F5: int
K_F6: int
K_F7: int
K_F8: int
K_F9: int
K_F10: int
K_F11: int
K_F12: int
K_F13: int
K_F14: int
K_F15: int
K_NUMLOCK: int
K_CAPSLOCK: int
K_SCROLLOCK: int
K_RSHIFT: int
K_LSHIFT: int
K_RCTRL: int
K_LCTRL: int
K_RALT: int
K_LALT: int
K_RMETA: int
K_LMETA: int
K_LSUPER: int
K_RSUPER: int
K_MODE: int
K_HELP: int
K_PRINT: int
K_SYSREQ: int
K_BREAK: int
K_MENU: int
K_POWER: int
K_EURO: int

# modifier information is contained in the mod attribute of the
# pygame.KEYDOWN and pygame.KEYUP events. The mod attribute is
# a bitmask of all the modifier keys that were in a pressed
# state when the event occurred
KMOD_NONE: int
KMOD_LSHIFT: int
KMOD_RSHIFT: int
KMOD_SHIFT: int
KMOD_LCTRL: int
KMOD_RCTRL: int
KMOD_CTRL: int
KMOD_LALT: int
KMOD_RALT: int
KMOD_ALT: int
KMOD_LMETA: int
KMOD_RMETA: int
KMOD_META: int
KMOD_CAPS: int
KMOD_NUM: int
KMOD_MODE: int