from typing import Tuple

from .rect import Rect

class Surface:
    def convert_alpha(self) -> Surface: ...
    def get_rect(self) -> Rect: ...
    def get_width(self) -> int: ...
    def get_height(self) -> int: ...
    def get_at(self, top_left: Tuple[int, int]) -> Color: ...
    def subsurface(self, rect: Rect) -> Surface: ...

class Color:
    r: int
    g: int
    b: int
    a: int

